version: "3.9"
services:
  db:
    image: "postgres"
    hostname: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=etl
      - POSTGRES_PASSWORD=etl
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    healthcheck:
        test: pg_isready -U etl -d db
        interval: 30s
        timeout: 10s
        retries: 5
  etl:
    build: etl
    restart: on-failure
    depends_on:
      - db
    links:
      - db
  ml:
    build: ml
    restart: on-failure
    depends_on:
      - db
      - etl
    links:
      - db
volumes:
  postgres-data: